set termencoding=utf-8

set fileformats=unix,dos,mac
if exists('&ambiwidth')
  set ambiwidth=double
endif

syntax on
set background=dark
set backspace=indent,eol,start
set number
set expandtab 
set shiftwidth=4 
set softtabstop=4
set autoindent
set smartindent
set mouse=a
set cursorline
set hlsearch
set incsearch
set title
set wildmenu wildmode=list:full
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end

set t_Co=256
hi CursorLine cterm=NONE ctermbg=234
hi Visual term=reverse cterm=reverse
hi Pmenu ctermbg=darkgray ctermfg=lightgray
hi PmenuSel ctermbg=darkblue ctermfg=yellow
hi PmenuSbar ctermbg=darkred
hi Comment ctermfg=darkgreen

au BufNewFile,BufRead *.jbuilder set filetype=ruby
if has("autocmd")
    autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
    autocmd Filetype html setlocal ts=2 sw=2 expandtab
    autocmd Filetype eruby setlocal ts=2 sw=2 expandtab
    autocmd Filetype yaml setlocal ts=2 sw=2 expandtab
    autocmd BufReadPost *
    \ if line("'\"") > 0 && line ("'\"") <= line("$") |
    \   exe "normal! g'\"" |
    \ endif
endif

noremap ; :
noremap : ;
noremap /  /\v
nnoremap n nzz
nnoremap N Nzz
nnoremap <silent> <C-L> :noh<C-L><CR>

inoremap <C-e> <Esc>$a
inoremap <C-a> <Esc>^i
noremap <C-e> <Esc>$a
noremap <C-a> <Esc>^i

set pastetoggle=<F9>

set laststatus=2
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

if &diff
    set diffopt+=iwhite
    hi DiffAdd    ctermfg=black ctermbg=2
    hi DiffChange ctermfg=black ctermbg=3
    hi DiffDelete ctermfg=black ctermbg=6
    hi DiffText   ctermfg=black ctermbg=7
endif


if 0 | endif

if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath^=~/.vim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!
" Add or remove your Bundles here:
NeoBundle 'Shougo/context_filetype.vim'

" toogle comment plugin
NeoBundle "tyru/caw.vim.git"
nmap <C-_> <Plug>(caw:hatpos:toggle)
vmap <C-_> <Plug>(caw:hatpos:toggle)

" show file directories tree
NeoBundle 'scrooloose/nerdtree'
nnoremap <silent><C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" visually displaying indent levels in code
NeoBundle "Yggdroot/indentLine"
let g:indentLine_color_term = 239
let g:indentLine_conceallevel = 0

NeoBundle 'Shougo/neocomplete.vim'
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3
" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  " return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
  " For no inserting <CR> key.
  return pumvisible() ? "\<C-y>" : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"

NeoBundle 'elzr/vim-json'
let g:vim_json_syntax_conceal = 0
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
